language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t hassanalthaf/react-app  -f Dockerfile.dev .
script:
  - docker run -e CI=true hassanalthaf/react-app npm run test
