FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# docker run -it -p 3000:3000 -v /app/node_modules -v /d/Projects/docker/react-app:/app hassanalthaf/react-app
