FROM node:16-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]

# docker run -it -p 3000:3000 -v /app/node_modules -v /d/Projects/docker/react-app:/app hassanalthaf/react-app
